image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - frontend/node_modules/

build_front_end:
  stage: build
  script:
    - cd frontend
    - npm install
    - CI=false npm run-script build