image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - frontend/node_modules/

frontend_build:
  stage: build
  script:
    - cd frontend
    - npm install
    - CI=false npm run-script build

postman_test:
  stage: test
  script:
    - npm install -g newman
    - cd backend
    - newman run collection.json

frontend_gui_test:
  stage: test
  image: python:latest
  script:
  - cd frontend
  - pip3 install -r selenium
  - python3 guitests.py

backend_unit_tests:
  stage: test
  image: python:latest
  script:
    - cd backend
    - pip3 install -r requirements.txt
    - python3 tests.py

